config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  # search query
  #"/" = root URL pointing to 'home#index' controller
  post "/" => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ edit update destroy]
  
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_50b7099e20a147dbaaea15e037a2e9f1')

    # FOR SEARCH QUERY
    # once the form filled out, send "ticker" params to the StockQuote
    # and return the result to @stock instance variable

    # error handling
     # to check if params has empty value
    if params[:ticker] == ""
      @empty_error_msg = "Please Enter A Stock Symbol!"
    elsif params[:ticker]
      @stock = StockQuote::Stock.quote(params[:ticker])
        # to check if params has junk or gibberish value
      if !@stock
          @junk_error_msg = "Stock Symbol Doesn't Exist. Please Try Again!"
      end
    end
  end

  def about 
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ edit update destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "You are not authorized to edit this stock!" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_footer.html.erb
<center>Copyright (c) Test Footers</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Stock Market", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link" %>
        </li>

        <%# conditional navbar links %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Portfolio", stocks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Buy Stock", new_stock_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
    </div>

  </div>
</nav>

app/views/home/about.html.erb
<body>
    <h1> About Me <h1/>
    <p> Hello! This is an about me page <p/>
<body/>

app/views/home/index.html.erb
<title>Stock Market App</title>
<h1>Stock Market App</h1>
<%# StockQuote::Stock.new(api_key: 'pk_50b7099e20a147dbaaea15e037a2e9f1') %>

 <%# SEARCH FORM %>
 <%# filled out form sends it as a parameter (params) and params name is whatever the text field is called"%>
<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter Stock Symbol", size: 50 %>
    <%= submit_tag 'Search' %>
<% end %>

<br/> 

<%# error handling %>
<%# to display if @stock instance has value %>
<% if @stock %>
    Company Name: <%= @stock.company_name %><br/>
    Latest Price: $<%= @stock.latest_price %><br/>
<% elsif @empty_error_msg %>
    <%= @empty_error_msg %>
<% end %>
<%# to display if @stock instance has junk or gibberish value %>
<% if @junk_error_msg %>
    <%= @junk_error_msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render 'home/navbar' %>

  <div class="container">
    <%= render 'home/flash' %>
    <br/>
    <%= yield %>
  </div>

  <%= render 'home/footer' %>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
</body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<head>
<link rel="stylesheet" href="style.css">
</head>

<h2>My Stocks</h2>
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover">
    <tr>
     <thead class="table-dark">
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
      </thead>
    </tr>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <% begin %>
            <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
        <% rescue StandardError %>
        <tr>
          <td><%= link_to "Error! Stock does not exist.", stock %></td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to @ticker.company_name, stock %></td>
          <td><%= @ticker.symbol %></td>
          <td>$<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %></td>
          <td>$<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %></td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br/>

<%= link_to 'Get Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% @api = StockQuote::Stock.new(api_key: 'pk_50b7099e20a147dbaaea15e037a2e9f1') %>

<% begin %>
    <% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
    <% @logo = StockQuote::Stock.logo(@stock.ticker)%>
    <img src="<%= @logo.url %>"><br/><br/>
    <h2><%= @ticker.company_name %></h2><br/>
    Ticker Symbol: <%= @ticker.symbol %><br/>
    Latest Price: $<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %><br/>
    Previous Close: $<%= number_with_precision(@ticker.previous_close, :precision => 2, :delimiter => ',') %><br/>
    Percent Change: <%= @ticker.change_percent %>%<br/>
    YTD Change: <%= number_with_precision(@ticker.ytd_change, :precision => 2, :delimiter => ',') %>%<br/>
    Market Cap: $<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %><br/>
<% rescue StandardError %>
    The ticker: <%= @stock.ticker %> does not exist!<br/>
<% end %>
<%= link_to 'Edit', edit_stock_path(@stock) %>
<%= link_to 'Back', stocks_path %>